
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: teams_app_development

test:
  <<: *default
  database: teams_app_test

production:
  <<: *default
  database: teams_app_production
  username: teams_app
  password: <%= ENV['TEAMS_APP_DATABASE_PASSWORD'] %>
